spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://192.168.244.128:3306/school?useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
